# Change these first
owner: budlebee # Your GitHub organization or username, where this repository lives
repo: upptime-kundera # The name of this repository

sites:
  - name: Kundera
    url: https://kundera.so
  - name: Foresty
    url: https://foresty.net
  - name: Videoglancer
    url: https://videoglancer.com
  - name: tect.dev
    url: https://tect.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime-kundera # where "repo" is your repository name
  name: upptime-kundera
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: upptime-kundera
  introTitle: "쿤데라는 오픈소스 Upptime 과 Github Action 을 통해 모니터링 되고 있습니다."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Budlebee
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
